[project]
name = 'Decentralized-Commercial-Lending-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.borrower-verification]
path = 'contracts/borrower-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.collateral-registration]
path = 'contracts/collateral-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
